name: Generate AUST Notice RSS Feed

on:
  schedule:
    # Bangladesh time (UTC+6) schedule:
    # 8 AM - 12 PM: Run hourly (2-6 UTC)
    - cron: '0 2-6 * * *'
    # 7 PM - 12 AM: Run hourly (13-18 UTC)
    - cron: '0 13-18 * * *'
    # In between: Run every 3 hours (9,12 UTC)
    - cron: '0 9,12 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: write # Allow the job to commit changes back to the repository

jobs:
  build_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Use latest checkout action

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Choose a suitable Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run script to generate RSS feed
        run: python generate-rss.py

      - name: Commit and push if feed changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Check if the feed file was modified or created
          if [[ `git status --porcelain feed.xml` ]]; then
            git add feed.xml
            git commit -m "Update RSS feed - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            echo "Pushing changes..."
            git push
          else
            echo "No changes detected in feed.xml."
          fi