name: Generate AUST Notice RSS Feed

on:
  schedule:
    # Run every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: write # Allow the job to commit changes back to the repository

jobs:
  build_feed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Use latest checkout action

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Choose a suitable Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run script to generate RSS feed
        run: python generate-rss.py

      - name: Commit and push if feed changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Check if the feed file was modified or created
          if [[ `git status --porcelain feed.xml` ]]; then
            git add feed.xml
            git commit -m "Update RSS feed - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            echo "Pushing changes..."
            git push
          else
            echo "No changes detected in feed.xml."
          fi

  build_shed_scholarship_feed:
    runs-on: ubuntu-latest
    needs: build_feed
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run script to generate shed.gov.bd scholarship RSS feed
        run: python generate-shed-scholarship-rss.py

      - name: Commit and push if shed_scholarship_feed.xml changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ `git status --porcelain shed_scholarship_feed.xml` ]]; then
            git add shed_scholarship_feed.xml
            git commit -m "Update shed.gov.bd scholarship RSS feed - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            echo "Pushing changes..."
            git push
          else
            echo "No changes detected in shed_scholarship_feed.xml."
          fi